dist: bionic
language: php

env:
  global:
    - SETUP=stable
    - LOWEST=6.0
    - COMPOSER_MEMORY_LIMIT=-1

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: COMPOSER=composer.dingo.json
      name: "With Dingo router"
    - php: 7.4
      env: SETUP=lint
      name: "Lint code"
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4
    - php: 7.4
      env: SETUP=lowest

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --prefer-stable; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer require laravel/framework:^$LOWEST; composer require laravel/lumen-framework:^$LOWEST; fi
  - if [[ $SETUP = 'lint' ]]; then travis_retry composer update --prefer-dist --prefer-stable; composer lint; fi

script:
  - if [[ $SETUP = 'lint' ]]; then exit 0; fi; composer test-parallel-ci;
